name: Weekly Bluesky Post

on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmagick++-dev

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("atrrr", "magick", "rgbif"))'

    - name: Run R script
      env:
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
      run: |
        Rscript Taxo_bot.R
